### ISSUE TITLE
Doesn't work on windows?

### ISSUE THREAD

**Issue by seanmcilvenna** [revolunet/node-readme#4]
Love the idea behind this project... But can't seem to get it to work on windows.
Get this error:

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

The command it is failing on seems to be expecting linux, not windows.

**Comment by vladimirmelekh** [comment]
I have the same issue, win8. Is there a way to fix it?

**Comment by revolunet** [comment]
Mmm this is some bash scripts so they may not be windows friendly :/
